#!/bin/bash
hoje=$(date +"%d%m%y")
echo " "
echo "Informe o dominio: "
read DOM
mkdir $DOM-$hoje; cd $DOM-$hoje;
clear

#cria arq CRT
TMP="$(mktemp)" || exit 1
echo "Arquivo CRT: (*atalho "dd" apaga a linha atual)" > "$TMP"
vim "$TMP"
cat "$TMP" > $DOM.crt

#cria arq KEY
TMP="$(mktemp)" || exit 1
echo "Arquivo KEY: " > "$TMP"
vim "$TMP"
cat "$TMP" > $DOM.key
clear 

#cria arq CA
echo "-----BEGIN CERTIFICATE-----
MIIETTCCAzWgAwIBAgILBAAAAAABRE7wNjEwDQYJKoZIhvcNAQELBQAwVzELMAkG
A1UEBhMCQkUxGTAXBgNVBAoTEEdsb2JhbFNpZ24gbnYtc2ExEDAOBgNVBAsTB1Jv
b3QgQ0ExGzAZBgNVBAMTEkdsb2JhbFNpZ24gUm9vdCBDQTAeFw0xNDAyMjAxMDAw
MDBaFw0yNDAyMjAxMDAwMDBaMEwxCzAJBgNVBAYTAkJFMRkwFwYDVQQKExBHbG9i
YWxTaWduIG52LXNhMSIwIAYDVQQDExlBbHBoYVNTTCBDQSAtIFNIQTI1NiAtIEcy
MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEA2gHs5OxzYPt+j2q3xhfj
kmQy1KwA2aIPue3ua4qGypJn2XTXXUcCPI9A1p5tFM3D2ik5pw8FCmiiZhoexLKL
dljlq10dj0CzOYvvHoN9ItDjqQAu7FPPYhmFRChMwCfLew7sEGQAEKQFzKByvkFs
MVtI5LHsuSPrVU3QfWJKpbSlpFmFxSWRpv6mCZ8GEG2PgQxkQF5zAJrgLmWYVBAA
cJjI4e00X9icxw3A1iNZRfz+VXqG7pRgIvGu0eZVRvaZxRsIdF+ssGSEj4k4HKGn
kCFPAm694GFn1PhChw8K98kEbSqpL+9Cpd/do1PbmB6B+Zpye1reTz5/olig4het
ZwIDAQABo4IBIzCCAR8wDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
AQAwHQYDVR0OBBYEFPXN1TwIUPlqTzq3l9pWg+Zp0mj3MEUGA1UdIAQ+MDwwOgYE
VR0gADAyMDAGCCsGAQUFBwIBFiRodHRwczovL3d3dy5hbHBoYXNzbC5jb20vcmVw
b3NpdG9yeS8wMwYDVR0fBCwwKjAooCagJIYiaHR0cDovL2NybC5nbG9iYWxzaWdu
Lm5ldC9yb290LmNybDA9BggrBgEFBQcBAQQxMC8wLQYIKwYBBQUHMAGGIWh0dHA6
Ly9vY3NwLmdsb2JhbHNpZ24uY29tL3Jvb3RyMTAfBgNVHSMEGDAWgBRge2YaRQ2X
yolQL30EzTSo//z9SzANBgkqhkiG9w0BAQsFAAOCAQEAYEBoFkfnFo3bXKFWKsv0
XJuwHqJL9csCP/gLofKnQtS3TOvjZoDzJUN4LhsXVgdSGMvRqOzm+3M+pGKMgLTS
xRJzo9P6Aji+Yz2EuJnB8br3n8NA0VgYU8Fi3a8YQn80TsVD1XGwMADH45CuP1eG
l87qDBKOInDjZqdUfy4oy9RU0LMeYmcI+Sfhy+NmuCQbiWqJRGXy2UzSWByMTsCV
odTvZy84IOgu/5ZR8LrYPZJwR2UcnnNytGAMXOLRc3bgr07i5TelRS+KIz6HxzDm
MTh89N1SyvNTBCVXVmaU6Avu5gMUTu79bZRknl7OedSyps9AsUSoPocZXun4IRZZ
Uw==
-----END CERTIFICATE-----" > $DOM.ca;

#Valida se o host é CPROGERLIN e gera o $USER pem
VAL=$(echo $HOSTNAME | cut -c 1-10)

if [ "$VAL" = "cprogerlin" ]; then
    cat $DOM.key $DOM.crt > $DOM.pem
echo " "		
echo "

      # ###                                                                                      ###        
    /  /###  /                                                                                    ###       
   /  /  ###/                                     #                                                ##       
  /  ##   ##                                     ##                                                ##       
 /  ###                                          ##                                                ##       
##   ##            /##  ###  /###     /###     ######## /###   ###  /###          /###     /###    ##       
##   ##   ###     / ###  ###/ #### / / ###  / ######## / ###  / ###/ #### /      / #### / / #### / ##       
##   ##  /###  / /   ###  ##   ###/ /   ###/     ##   /   ###/   ##   ###/      ##  ###/ ##  ###/  ##       
##   ## /  ###/ ##    ### ##       ##    ##      ##  ##    ##    ##            ####     ####       ##       
##   ##/    ##  ########  ##       ##    ##      ##  ##    ##    ##              ###      ###      ##       
 ##  ##     #   #######   ##       ##    ##      ##  ##    ##    ##                ###      ###    ##       
  ## #      /   ##        ##       ##    ##      ##  ##    ##    ##                  ###      ###  ##       
   ###     /    ####    / ##       ##    /#      ##  ##    ##    ##             /###  ## /###  ##  ##       
    ######/      ######/  ###       ####/ ##     ##   ######     ###           / #### / / #### /   ### /    
      ###         #####    ###       ###   ##     ##   ####       ###             ###/     ###/     ##/     

"
echo "Caminho completo dos arquivos: "; ls -1 | sed "s#^#${PWD}/#" 
echo " "
echo "CRT / KEY Matcher:"
echo "openssl x509 -noout -modulus -in $DOM.crt | openssl md5 &&
openssl rsa -noout -modulus -in $DOM.key | openssl md5"
openssl x509 -noout -modulus -in $DOM.crt | openssl md5 &&
openssl rsa -noout -modulus -in $DOM.key | openssl md5
echo " "

else

#####################Padrão#############################
echo " "		
echo "

      # ###                                                                                      ###        
    /  /###  /                                                                                    ###       
   /  /  ###/                                     #                                                ##       
  /  ##   ##                                     ##                                                ##       
 /  ###                                          ##                                                ##       
##   ##            /##  ###  /###     /###     ######## /###   ###  /###          /###     /###    ##       
##   ##   ###     / ###  ###/ #### / / ###  / ######## / ###  / ###/ #### /      / #### / / #### / ##       
##   ##  /###  / /   ###  ##   ###/ /   ###/     ##   /   ###/   ##   ###/      ##  ###/ ##  ###/  ##       
##   ## /  ###/ ##    ### ##       ##    ##      ##  ##    ##    ##            ####     ####       ##       
##   ##/    ##  ########  ##       ##    ##      ##  ##    ##    ##              ###      ###      ##       
 ##  ##     #   #######   ##       ##    ##      ##  ##    ##    ##                ###      ###    ##       
  ## #      /   ##        ##       ##    ##      ##  ##    ##    ##                  ###      ###  ##       
   ###     /    ####    / ##       ##    /#      ##  ##    ##    ##             /###  ## /###  ##  ##       
    ######/      ######/  ###       ####/ ##     ##   ######     ###           / #### / / #### /   ### /    
      ###         #####    ###       ###   ##     ##   ####       ###             ###/     ###/     ##/     

"
echo " "
echo "Caminho completo dos arquivos: "; ls -1 | sed "s#^#${PWD}/#"
echo " "
echo "CRT / KEY Matcher:"
echo "openssl x509 -noout -modulus -in $DOM.crt | openssl md5 &&
openssl rsa -noout -modulus -in $UDOM.key | openssl md5"
openssl x509 -noout -modulus -in $DOM.crt | openssl md5 &&
openssl rsa -noout -modulus -in $DOM.key | openssl md5
echo " "

fi

rm ~/ssl.sh

